version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=${PORT}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped