-- CreateTable
CREATE TABLE `nb_assistants` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `ASSISTANT_ID` VARCHAR(255) NULL,
    `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DESCRIPTION` VARCHAR(255) NULL,
    `NAME` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_casino_records` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `AMOUNT` BIGINT NOT NULL,
    `BET_AMOUNT` BIGINT NOT NULL,
    `RESULT` VARCHAR(255) NOT NULL,
    `TIMESTAMP` DATETIME(6) NOT NULL,
    `USER_ID` VARCHAR(255) NOT NULL,
    `WIN_PROBABILITY` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_casino_servers` (
    `ID` VARCHAR(255) NOT NULL,
    `NAME` VARCHAR(255) NULL,
    `TIMESTAMP` DATETIME(6) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_casino_users` (
    `ID` VARCHAR(255) NOT NULL,
    `BALANCE` BIGINT NULL,
    `LAST_RECEIVED_MONEY_TIME` DATETIME(6) NULL,
    `USERNAME` VARCHAR(255) NULL,
    `SERVER_ID` VARCHAR(255) NULL,
    `TOTAL_BETS` BIGINT NULL,
    `TOTAL_LOSSES` BIGINT NULL,
    `TOTAL_WINS` BIGINT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_channels` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `CHANNEL_ID` VARCHAR(255) NULL,
    `CHANNEL_NAME` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_chat_messages` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `CONTENT` LONGTEXT NOT NULL,
    `CONVERSATION_ID` VARCHAR(255) NULL,
    `IS_BOT_MESSAGE` BOOLEAN NULL,
    `IS_DELETED` BOOLEAN NOT NULL,
    `THREAD_ID` VARCHAR(255) NULL,
    `TIMESTAMP` DATETIME(6) NULL,
    `USER_ID` BIGINT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_chat_users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `CONTEXT_ENABLED` BOOLEAN NULL,
    `DISCORD_ID` VARCHAR(255) NOT NULL,
    `LAST_CONVERSATION_ID` VARCHAR(255) NULL,
    `LAST_INTERACTION` DATETIME(6) NULL,
    `TIMESTAMP` DATETIME(6) NULL,
    `USERNAME` VARCHAR(255) NULL,

    UNIQUE INDEX `nb_chat_users_DISCORD_ID_key`(`DISCORD_ID`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `nb_posts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `CHANNEL_ID` VARCHAR(255) NULL,
    `IS_SENT` BOOLEAN NOT NULL,
    `LINK` VARCHAR(255) NULL,
    `POST_ID` VARCHAR(255) NULL,
    `TIMESTAMP` DATETIME(6) NULL,
    `TITLE` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `nb_casino_records` ADD CONSTRAINT `nb_casino_records_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `nb_casino_users`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `nb_casino_users` ADD CONSTRAINT `nb_casino_users_SERVER_ID_fkey` FOREIGN KEY (`SERVER_ID`) REFERENCES `nb_casino_servers`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `nb_chat_messages` ADD CONSTRAINT `nb_chat_messages_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `nb_chat_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
